name: Run Java Tests

on:
  push:
    branches:
      - main
      - backend
      - release-candidate

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Se dan permisos de ejecución a Maven Wrapper
        run: chmod +x mvnw
      - name: Build and run tests
        run: ./mvnw test

      - name : Build JAR
        run: ./mvnw package -DskipTests

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v4
        with:
          name: App-biblioteca-jar
          path: target/*.jar
