name: Build and push Docker image

on:
  push:
    branches:
      - main
      - backend
      - release-candidate

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Give execute permissions to Maven Wrapper
        run: chmod +x mvnw

      - name: Run tests with Maven
        run: mvn test

      - name: Build JAR
        run: mvn clean package

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t renatobs24/app-biblioteca:latest .

      - name: Push Docker image
        run: docker push renatobs24/app-biblioteca:latest